# Generated by Django 4.0.6 on 2022-09-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreRol', models.CharField(choices=[('Admin', 'Administrador'), ('Cl', 'Cliente'), ('Ds', 'Diseñador')], default='Cl', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPatron', models.CharField(max_length=254)),
                ('descripcion', models.TextField(default='Pendiente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=10)),
                ('NombreRol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DesignCal.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Patrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(default='Pendiente')),
                ('precio', models.BigIntegerField(default=0)),
                ('archivo', models.FileField(default=None, upload_to='DesignCal/files')),
                ('imagen', models.ImageField(default='DesignCal/fotos/default.jpg', upload_to='DesignCal/fotos')),
                ('tipoPatron', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DesignCal.tipopatron')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DesignCal.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('nombreArchivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DesignCal.patrone')),
            ],
        ),
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, unique=True)),
                ('contenido', models.CharField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DesignCal.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='Pendiente', max_length=250)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('CP', 'Completo'), ('C', 'Cancelado')], default='P', max_length=2)),
                ('IdFactura', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='DesignCal.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DesignCal.usuario')),
            ],
        ),
    ]
