# Generated by Django 4.0.6 on 2022-09-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignCal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='NombreRol',
            field=models.CharField(default='Cliente', max_length=20),
        ),
    ]
