# Generated by Django 4.0.6 on 2022-10-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignCal', '0002_alter_rol_nombrerol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(default='DesignCal/fotosPerfil/default.jpg', upload_to='DesignCal/fotosPerfil'),
        ),
    ]
